name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixar o código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Node.js  e configurar cache do pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 3️⃣ Instalar pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 4️⃣ Instalar dependências
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5️⃣ Build do projeto
      - name: Build Next.js project
        run: pnpm run build
